// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: nlp.proto

package nlpv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_nlp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nlp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_nlp_proto_rawDescGZIP(), []int{0}
}

type HealthResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Service         string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Status          string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	PipelineVersion string                 `protobuf:"bytes,3,opt,name=pipeline_version,json=pipelineVersion,proto3" json:"pipeline_version,omitempty"`
	EmbeddingModel  string                 `protobuf:"bytes,4,opt,name=embedding_model,json=embeddingModel,proto3" json:"embedding_model,omitempty"`
	EmbeddingDim    int32                  `protobuf:"varint,5,opt,name=embedding_dim,json=embeddingDim,proto3" json:"embedding_dim,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_nlp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nlp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_nlp_proto_rawDescGZIP(), []int{1}
}

func (x *HealthResponse) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetPipelineVersion() string {
	if x != nil {
		return x.PipelineVersion
	}
	return ""
}

func (x *HealthResponse) GetEmbeddingModel() string {
	if x != nil {
		return x.EmbeddingModel
	}
	return ""
}

func (x *HealthResponse) GetEmbeddingDim() int32 {
	if x != nil {
		return x.EmbeddingDim
	}
	return 0
}

type AnalyzeDocumentRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProjectId       string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	DocumentId      string                 `protobuf:"bytes,2,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	Passages        []*PassageInput        `protobuf:"bytes,3,rep,name=passages,proto3" json:"passages,omitempty"`
	LanguageHint    string                 `protobuf:"bytes,4,opt,name=language_hint,json=languageHint,proto3" json:"language_hint,omitempty"`
	CustomStopwords []string               `protobuf:"bytes,5,rep,name=custom_stopwords,json=customStopwords,proto3" json:"custom_stopwords,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AnalyzeDocumentRequest) Reset() {
	*x = AnalyzeDocumentRequest{}
	mi := &file_nlp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeDocumentRequest) ProtoMessage() {}

func (x *AnalyzeDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nlp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeDocumentRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeDocumentRequest) Descriptor() ([]byte, []int) {
	return file_nlp_proto_rawDescGZIP(), []int{2}
}

func (x *AnalyzeDocumentRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *AnalyzeDocumentRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *AnalyzeDocumentRequest) GetPassages() []*PassageInput {
	if x != nil {
		return x.Passages
	}
	return nil
}

func (x *AnalyzeDocumentRequest) GetLanguageHint() string {
	if x != nil {
		return x.LanguageHint
	}
	return ""
}

func (x *AnalyzeDocumentRequest) GetCustomStopwords() []string {
	if x != nil {
		return x.CustomStopwords
	}
	return nil
}

type PassageInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PassageId     string                 `protobuf:"bytes,1,opt,name=passage_id,json=passageId,proto3" json:"passage_id,omitempty"`
	Sentences     []*SentenceInput       `protobuf:"bytes,2,rep,name=sentences,proto3" json:"sentences,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PassageInput) Reset() {
	*x = PassageInput{}
	mi := &file_nlp_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PassageInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PassageInput) ProtoMessage() {}

func (x *PassageInput) ProtoReflect() protoreflect.Message {
	mi := &file_nlp_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PassageInput.ProtoReflect.Descriptor instead.
func (*PassageInput) Descriptor() ([]byte, []int) {
	return file_nlp_proto_rawDescGZIP(), []int{3}
}

func (x *PassageInput) GetPassageId() string {
	if x != nil {
		return x.PassageId
	}
	return ""
}

func (x *PassageInput) GetSentences() []*SentenceInput {
	if x != nil {
		return x.Sentences
	}
	return nil
}

type SentenceInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SentenceId    string                 `protobuf:"bytes,1,opt,name=sentence_id,json=sentenceId,proto3" json:"sentence_id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	StartChar     int64                  `protobuf:"varint,3,opt,name=start_char,json=startChar,proto3" json:"start_char,omitempty"`
	EndChar       int64                  `protobuf:"varint,4,opt,name=end_char,json=endChar,proto3" json:"end_char,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SentenceInput) Reset() {
	*x = SentenceInput{}
	mi := &file_nlp_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SentenceInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SentenceInput) ProtoMessage() {}

func (x *SentenceInput) ProtoReflect() protoreflect.Message {
	mi := &file_nlp_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SentenceInput.ProtoReflect.Descriptor instead.
func (*SentenceInput) Descriptor() ([]byte, []int) {
	return file_nlp_proto_rawDescGZIP(), []int{4}
}

func (x *SentenceInput) GetSentenceId() string {
	if x != nil {
		return x.SentenceId
	}
	return ""
}

func (x *SentenceInput) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SentenceInput) GetStartChar() int64 {
	if x != nil {
		return x.StartChar
	}
	return 0
}

func (x *SentenceInput) GetEndChar() int64 {
	if x != nil {
		return x.EndChar
	}
	return 0
}

type AnalyzeDocumentResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PipelineVersion   string                 `protobuf:"bytes,1,opt,name=pipeline_version,json=pipelineVersion,proto3" json:"pipeline_version,omitempty"`
	SentenceLanguages []*SentenceLanguage    `protobuf:"bytes,2,rep,name=sentence_languages,json=sentenceLanguages,proto3" json:"sentence_languages,omitempty"`
	Tokens            []*Token               `protobuf:"bytes,3,rep,name=tokens,proto3" json:"tokens,omitempty"`
	Mentions          []*EntityMention       `protobuf:"bytes,4,rep,name=mentions,proto3" json:"mentions,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AnalyzeDocumentResponse) Reset() {
	*x = AnalyzeDocumentResponse{}
	mi := &file_nlp_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeDocumentResponse) ProtoMessage() {}

func (x *AnalyzeDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nlp_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeDocumentResponse.ProtoReflect.Descriptor instead.
func (*AnalyzeDocumentResponse) Descriptor() ([]byte, []int) {
	return file_nlp_proto_rawDescGZIP(), []int{5}
}

func (x *AnalyzeDocumentResponse) GetPipelineVersion() string {
	if x != nil {
		return x.PipelineVersion
	}
	return ""
}

func (x *AnalyzeDocumentResponse) GetSentenceLanguages() []*SentenceLanguage {
	if x != nil {
		return x.SentenceLanguages
	}
	return nil
}

func (x *AnalyzeDocumentResponse) GetTokens() []*Token {
	if x != nil {
		return x.Tokens
	}
	return nil
}

func (x *AnalyzeDocumentResponse) GetMentions() []*EntityMention {
	if x != nil {
		return x.Mentions
	}
	return nil
}

type SentenceLanguage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SentenceId    string                 `protobuf:"bytes,1,opt,name=sentence_id,json=sentenceId,proto3" json:"sentence_id,omitempty"`
	Language      string                 `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`
	Confidence    float32                `protobuf:"fixed32,3,opt,name=confidence,proto3" json:"confidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SentenceLanguage) Reset() {
	*x = SentenceLanguage{}
	mi := &file_nlp_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SentenceLanguage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SentenceLanguage) ProtoMessage() {}

func (x *SentenceLanguage) ProtoReflect() protoreflect.Message {
	mi := &file_nlp_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SentenceLanguage.ProtoReflect.Descriptor instead.
func (*SentenceLanguage) Descriptor() ([]byte, []int) {
	return file_nlp_proto_rawDescGZIP(), []int{6}
}

func (x *SentenceLanguage) GetSentenceId() string {
	if x != nil {
		return x.SentenceId
	}
	return ""
}

func (x *SentenceLanguage) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *SentenceLanguage) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

type Token struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SentenceId    string                 `protobuf:"bytes,1,opt,name=sentence_id,json=sentenceId,proto3" json:"sentence_id,omitempty"`
	TokenIndex    int32                  `protobuf:"varint,2,opt,name=token_index,json=tokenIndex,proto3" json:"token_index,omitempty"`
	Surface       string                 `protobuf:"bytes,3,opt,name=surface,proto3" json:"surface,omitempty"`
	Lemma         string                 `protobuf:"bytes,4,opt,name=lemma,proto3" json:"lemma,omitempty"`
	Pos           string                 `protobuf:"bytes,5,opt,name=pos,proto3" json:"pos,omitempty"`
	IsStopword    bool                   `protobuf:"varint,6,opt,name=is_stopword,json=isStopword,proto3" json:"is_stopword,omitempty"`
	IsPunct       bool                   `protobuf:"varint,7,opt,name=is_punct,json=isPunct,proto3" json:"is_punct,omitempty"`
	StartChar     int64                  `protobuf:"varint,8,opt,name=start_char,json=startChar,proto3" json:"start_char,omitempty"`
	EndChar       int64                  `protobuf:"varint,9,opt,name=end_char,json=endChar,proto3" json:"end_char,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Token) Reset() {
	*x = Token{}
	mi := &file_nlp_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Token) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Token) ProtoMessage() {}

func (x *Token) ProtoReflect() protoreflect.Message {
	mi := &file_nlp_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Token.ProtoReflect.Descriptor instead.
func (*Token) Descriptor() ([]byte, []int) {
	return file_nlp_proto_rawDescGZIP(), []int{7}
}

func (x *Token) GetSentenceId() string {
	if x != nil {
		return x.SentenceId
	}
	return ""
}

func (x *Token) GetTokenIndex() int32 {
	if x != nil {
		return x.TokenIndex
	}
	return 0
}

func (x *Token) GetSurface() string {
	if x != nil {
		return x.Surface
	}
	return ""
}

func (x *Token) GetLemma() string {
	if x != nil {
		return x.Lemma
	}
	return ""
}

func (x *Token) GetPos() string {
	if x != nil {
		return x.Pos
	}
	return ""
}

func (x *Token) GetIsStopword() bool {
	if x != nil {
		return x.IsStopword
	}
	return false
}

func (x *Token) GetIsPunct() bool {
	if x != nil {
		return x.IsPunct
	}
	return false
}

func (x *Token) GetStartChar() int64 {
	if x != nil {
		return x.StartChar
	}
	return 0
}

func (x *Token) GetEndChar() int64 {
	if x != nil {
		return x.EndChar
	}
	return 0
}

type EntityMention struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SentenceId    string                 `protobuf:"bytes,1,opt,name=sentence_id,json=sentenceId,proto3" json:"sentence_id,omitempty"`
	Surface       string                 `protobuf:"bytes,2,opt,name=surface,proto3" json:"surface,omitempty"`
	NerLabel      string                 `protobuf:"bytes,3,opt,name=ner_label,json=nerLabel,proto3" json:"ner_label,omitempty"`
	MentionType   string                 `protobuf:"bytes,4,opt,name=mention_type,json=mentionType,proto3" json:"mention_type,omitempty"`
	Confidence    float32                `protobuf:"fixed32,5,opt,name=confidence,proto3" json:"confidence,omitempty"`
	StartChar     int64                  `protobuf:"varint,6,opt,name=start_char,json=startChar,proto3" json:"start_char,omitempty"`
	EndChar       int64                  `protobuf:"varint,7,opt,name=end_char,json=endChar,proto3" json:"end_char,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityMention) Reset() {
	*x = EntityMention{}
	mi := &file_nlp_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityMention) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityMention) ProtoMessage() {}

func (x *EntityMention) ProtoReflect() protoreflect.Message {
	mi := &file_nlp_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityMention.ProtoReflect.Descriptor instead.
func (*EntityMention) Descriptor() ([]byte, []int) {
	return file_nlp_proto_rawDescGZIP(), []int{8}
}

func (x *EntityMention) GetSentenceId() string {
	if x != nil {
		return x.SentenceId
	}
	return ""
}

func (x *EntityMention) GetSurface() string {
	if x != nil {
		return x.Surface
	}
	return ""
}

func (x *EntityMention) GetNerLabel() string {
	if x != nil {
		return x.NerLabel
	}
	return ""
}

func (x *EntityMention) GetMentionType() string {
	if x != nil {
		return x.MentionType
	}
	return ""
}

func (x *EntityMention) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *EntityMention) GetStartChar() int64 {
	if x != nil {
		return x.StartChar
	}
	return 0
}

func (x *EntityMention) GetEndChar() int64 {
	if x != nil {
		return x.EndChar
	}
	return 0
}

type EmbedPassagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Passages      []*PassageToEmbed      `protobuf:"bytes,1,rep,name=passages,proto3" json:"passages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedPassagesRequest) Reset() {
	*x = EmbedPassagesRequest{}
	mi := &file_nlp_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedPassagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedPassagesRequest) ProtoMessage() {}

func (x *EmbedPassagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nlp_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedPassagesRequest.ProtoReflect.Descriptor instead.
func (*EmbedPassagesRequest) Descriptor() ([]byte, []int) {
	return file_nlp_proto_rawDescGZIP(), []int{9}
}

func (x *EmbedPassagesRequest) GetPassages() []*PassageToEmbed {
	if x != nil {
		return x.Passages
	}
	return nil
}

type PassageToEmbed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PassageId     string                 `protobuf:"bytes,1,opt,name=passage_id,json=passageId,proto3" json:"passage_id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PassageToEmbed) Reset() {
	*x = PassageToEmbed{}
	mi := &file_nlp_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PassageToEmbed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PassageToEmbed) ProtoMessage() {}

func (x *PassageToEmbed) ProtoReflect() protoreflect.Message {
	mi := &file_nlp_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PassageToEmbed.ProtoReflect.Descriptor instead.
func (*PassageToEmbed) Descriptor() ([]byte, []int) {
	return file_nlp_proto_rawDescGZIP(), []int{10}
}

func (x *PassageToEmbed) GetPassageId() string {
	if x != nil {
		return x.PassageId
	}
	return ""
}

func (x *PassageToEmbed) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type EmbedPassagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelName     string                 `protobuf:"bytes,1,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	Dim           int32                  `protobuf:"varint,2,opt,name=dim,proto3" json:"dim,omitempty"`
	Embeddings    []*PassageEmbedding    `protobuf:"bytes,3,rep,name=embeddings,proto3" json:"embeddings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedPassagesResponse) Reset() {
	*x = EmbedPassagesResponse{}
	mi := &file_nlp_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedPassagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedPassagesResponse) ProtoMessage() {}

func (x *EmbedPassagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nlp_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedPassagesResponse.ProtoReflect.Descriptor instead.
func (*EmbedPassagesResponse) Descriptor() ([]byte, []int) {
	return file_nlp_proto_rawDescGZIP(), []int{11}
}

func (x *EmbedPassagesResponse) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *EmbedPassagesResponse) GetDim() int32 {
	if x != nil {
		return x.Dim
	}
	return 0
}

func (x *EmbedPassagesResponse) GetEmbeddings() []*PassageEmbedding {
	if x != nil {
		return x.Embeddings
	}
	return nil
}

type PassageEmbedding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PassageId     string                 `protobuf:"bytes,1,opt,name=passage_id,json=passageId,proto3" json:"passage_id,omitempty"`
	Values        []float32              `protobuf:"fixed32,2,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PassageEmbedding) Reset() {
	*x = PassageEmbedding{}
	mi := &file_nlp_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PassageEmbedding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PassageEmbedding) ProtoMessage() {}

func (x *PassageEmbedding) ProtoReflect() protoreflect.Message {
	mi := &file_nlp_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PassageEmbedding.ProtoReflect.Descriptor instead.
func (*PassageEmbedding) Descriptor() ([]byte, []int) {
	return file_nlp_proto_rawDescGZIP(), []int{12}
}

func (x *PassageEmbedding) GetPassageId() string {
	if x != nil {
		return x.PassageId
	}
	return ""
}

func (x *PassageEmbedding) GetValues() []float32 {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_nlp_proto protoreflect.FileDescriptor

const file_nlp_proto_rawDesc = "" +
	"\n" +
	"\tnlp.proto\x12\x12concordance.nlp.v1\"\x0f\n" +
	"\rHealthRequest\"\xbb\x01\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12)\n" +
	"\x10pipeline_version\x18\x03 \x01(\tR\x0fpipelineVersion\x12'\n" +
	"\x0fembedding_model\x18\x04 \x01(\tR\x0eembeddingModel\x12#\n" +
	"\rembedding_dim\x18\x05 \x01(\x05R\fembeddingDim\"\xe6\x01\n" +
	"\x16AnalyzeDocumentRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x1f\n" +
	"\vdocument_id\x18\x02 \x01(\tR\n" +
	"documentId\x12<\n" +
	"\bpassages\x18\x03 \x03(\v2 .concordance.nlp.v1.PassageInputR\bpassages\x12#\n" +
	"\rlanguage_hint\x18\x04 \x01(\tR\flanguageHint\x12)\n" +
	"\x10custom_stopwords\x18\x05 \x03(\tR\x0fcustomStopwords\"n\n" +
	"\fPassageInput\x12\x1d\n" +
	"\n" +
	"passage_id\x18\x01 \x01(\tR\tpassageId\x12?\n" +
	"\tsentences\x18\x02 \x03(\v2!.concordance.nlp.v1.SentenceInputR\tsentences\"~\n" +
	"\rSentenceInput\x12\x1f\n" +
	"\vsentence_id\x18\x01 \x01(\tR\n" +
	"sentenceId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x1d\n" +
	"\n" +
	"start_char\x18\x03 \x01(\x03R\tstartChar\x12\x19\n" +
	"\bend_char\x18\x04 \x01(\x03R\aendChar\"\x8b\x02\n" +
	"\x17AnalyzeDocumentResponse\x12)\n" +
	"\x10pipeline_version\x18\x01 \x01(\tR\x0fpipelineVersion\x12S\n" +
	"\x12sentence_languages\x18\x02 \x03(\v2$.concordance.nlp.v1.SentenceLanguageR\x11sentenceLanguages\x121\n" +
	"\x06tokens\x18\x03 \x03(\v2\x19.concordance.nlp.v1.TokenR\x06tokens\x12=\n" +
	"\bmentions\x18\x04 \x03(\v2!.concordance.nlp.v1.EntityMentionR\bmentions\"o\n" +
	"\x10SentenceLanguage\x12\x1f\n" +
	"\vsentence_id\x18\x01 \x01(\tR\n" +
	"sentenceId\x12\x1a\n" +
	"\blanguage\x18\x02 \x01(\tR\blanguage\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x02R\n" +
	"confidence\"\x81\x02\n" +
	"\x05Token\x12\x1f\n" +
	"\vsentence_id\x18\x01 \x01(\tR\n" +
	"sentenceId\x12\x1f\n" +
	"\vtoken_index\x18\x02 \x01(\x05R\n" +
	"tokenIndex\x12\x18\n" +
	"\asurface\x18\x03 \x01(\tR\asurface\x12\x14\n" +
	"\x05lemma\x18\x04 \x01(\tR\x05lemma\x12\x10\n" +
	"\x03pos\x18\x05 \x01(\tR\x03pos\x12\x1f\n" +
	"\vis_stopword\x18\x06 \x01(\bR\n" +
	"isStopword\x12\x19\n" +
	"\bis_punct\x18\a \x01(\bR\aisPunct\x12\x1d\n" +
	"\n" +
	"start_char\x18\b \x01(\x03R\tstartChar\x12\x19\n" +
	"\bend_char\x18\t \x01(\x03R\aendChar\"\xe4\x01\n" +
	"\rEntityMention\x12\x1f\n" +
	"\vsentence_id\x18\x01 \x01(\tR\n" +
	"sentenceId\x12\x18\n" +
	"\asurface\x18\x02 \x01(\tR\asurface\x12\x1b\n" +
	"\tner_label\x18\x03 \x01(\tR\bnerLabel\x12!\n" +
	"\fmention_type\x18\x04 \x01(\tR\vmentionType\x12\x1e\n" +
	"\n" +
	"confidence\x18\x05 \x01(\x02R\n" +
	"confidence\x12\x1d\n" +
	"\n" +
	"start_char\x18\x06 \x01(\x03R\tstartChar\x12\x19\n" +
	"\bend_char\x18\a \x01(\x03R\aendChar\"V\n" +
	"\x14EmbedPassagesRequest\x12>\n" +
	"\bpassages\x18\x01 \x03(\v2\".concordance.nlp.v1.PassageToEmbedR\bpassages\"C\n" +
	"\x0ePassageToEmbed\x12\x1d\n" +
	"\n" +
	"passage_id\x18\x01 \x01(\tR\tpassageId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"\x8e\x01\n" +
	"\x15EmbedPassagesResponse\x12\x1d\n" +
	"\n" +
	"model_name\x18\x01 \x01(\tR\tmodelName\x12\x10\n" +
	"\x03dim\x18\x02 \x01(\x05R\x03dim\x12D\n" +
	"\n" +
	"embeddings\x18\x03 \x03(\v2$.concordance.nlp.v1.PassageEmbeddingR\n" +
	"embeddings\"I\n" +
	"\x10PassageEmbedding\x12\x1d\n" +
	"\n" +
	"passage_id\x18\x01 \x01(\tR\tpassageId\x12\x16\n" +
	"\x06values\x18\x02 \x03(\x02R\x06values2\xaf\x02\n" +
	"\n" +
	"NLPService\x12O\n" +
	"\x06Health\x12!.concordance.nlp.v1.HealthRequest\x1a\".concordance.nlp.v1.HealthResponse\x12j\n" +
	"\x0fAnalyzeDocument\x12*.concordance.nlp.v1.AnalyzeDocumentRequest\x1a+.concordance.nlp.v1.AnalyzeDocumentResponse\x12d\n" +
	"\rEmbedPassages\x12(.concordance.nlp.v1.EmbedPassagesRequest\x1a).concordance.nlp.v1.EmbedPassagesResponseB2Z0concordance/services/api-go/internal/nlpv1;nlpv1b\x06proto3"

var (
	file_nlp_proto_rawDescOnce sync.Once
	file_nlp_proto_rawDescData []byte
)

func file_nlp_proto_rawDescGZIP() []byte {
	file_nlp_proto_rawDescOnce.Do(func() {
		file_nlp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nlp_proto_rawDesc), len(file_nlp_proto_rawDesc)))
	})
	return file_nlp_proto_rawDescData
}

var file_nlp_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_nlp_proto_goTypes = []any{
	(*HealthRequest)(nil),           // 0: concordance.nlp.v1.HealthRequest
	(*HealthResponse)(nil),          // 1: concordance.nlp.v1.HealthResponse
	(*AnalyzeDocumentRequest)(nil),  // 2: concordance.nlp.v1.AnalyzeDocumentRequest
	(*PassageInput)(nil),            // 3: concordance.nlp.v1.PassageInput
	(*SentenceInput)(nil),           // 4: concordance.nlp.v1.SentenceInput
	(*AnalyzeDocumentResponse)(nil), // 5: concordance.nlp.v1.AnalyzeDocumentResponse
	(*SentenceLanguage)(nil),        // 6: concordance.nlp.v1.SentenceLanguage
	(*Token)(nil),                   // 7: concordance.nlp.v1.Token
	(*EntityMention)(nil),           // 8: concordance.nlp.v1.EntityMention
	(*EmbedPassagesRequest)(nil),    // 9: concordance.nlp.v1.EmbedPassagesRequest
	(*PassageToEmbed)(nil),          // 10: concordance.nlp.v1.PassageToEmbed
	(*EmbedPassagesResponse)(nil),   // 11: concordance.nlp.v1.EmbedPassagesResponse
	(*PassageEmbedding)(nil),        // 12: concordance.nlp.v1.PassageEmbedding
}
var file_nlp_proto_depIdxs = []int32{
	3,  // 0: concordance.nlp.v1.AnalyzeDocumentRequest.passages:type_name -> concordance.nlp.v1.PassageInput
	4,  // 1: concordance.nlp.v1.PassageInput.sentences:type_name -> concordance.nlp.v1.SentenceInput
	6,  // 2: concordance.nlp.v1.AnalyzeDocumentResponse.sentence_languages:type_name -> concordance.nlp.v1.SentenceLanguage
	7,  // 3: concordance.nlp.v1.AnalyzeDocumentResponse.tokens:type_name -> concordance.nlp.v1.Token
	8,  // 4: concordance.nlp.v1.AnalyzeDocumentResponse.mentions:type_name -> concordance.nlp.v1.EntityMention
	10, // 5: concordance.nlp.v1.EmbedPassagesRequest.passages:type_name -> concordance.nlp.v1.PassageToEmbed
	12, // 6: concordance.nlp.v1.EmbedPassagesResponse.embeddings:type_name -> concordance.nlp.v1.PassageEmbedding
	0,  // 7: concordance.nlp.v1.NLPService.Health:input_type -> concordance.nlp.v1.HealthRequest
	2,  // 8: concordance.nlp.v1.NLPService.AnalyzeDocument:input_type -> concordance.nlp.v1.AnalyzeDocumentRequest
	9,  // 9: concordance.nlp.v1.NLPService.EmbedPassages:input_type -> concordance.nlp.v1.EmbedPassagesRequest
	1,  // 10: concordance.nlp.v1.NLPService.Health:output_type -> concordance.nlp.v1.HealthResponse
	5,  // 11: concordance.nlp.v1.NLPService.AnalyzeDocument:output_type -> concordance.nlp.v1.AnalyzeDocumentResponse
	11, // 12: concordance.nlp.v1.NLPService.EmbedPassages:output_type -> concordance.nlp.v1.EmbedPassagesResponse
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_nlp_proto_init() }
func file_nlp_proto_init() {
	if File_nlp_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nlp_proto_rawDesc), len(file_nlp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nlp_proto_goTypes,
		DependencyIndexes: file_nlp_proto_depIdxs,
		MessageInfos:      file_nlp_proto_msgTypes,
	}.Build()
	File_nlp_proto = out.File
	file_nlp_proto_goTypes = nil
	file_nlp_proto_depIdxs = nil
}
